spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

jpa:
  database: mysql
  hibernate:
    ddl-auto: update #自动更新
  show-sql: true  #开发阶段,打印要执行的sql语句.

logging:
  level:
    root: debug
