spring:
  application:
    name: admin-client

  profiles:
    active: prod

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  mail:
    host: smtp.qq.com
    port: 587
    username: wangkui24@foxmail.com
    password: wlxfawtntwvveege
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jpa:
  database: mysql
  hibernate:
    ddl-auto: update #自动更新
  show-sql: true  #开发阶段,打印要执行的sql语句.

logging:
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%X{trace_id}]) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
  level:
    root: info
  file: logs/app.log #添加开启admin的日志监控

private:
  key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArWvHReUF38nT0as1ziXryvJkbsS8MGgV8X4hzsicOJueoTSlUwsO2KUXjpLUiPPhIN0Mkr8R8gQcul5OXK30i/11ycx2LDDmGE7ako1Wr9PH0vmKCJmQBoDueH/YUJL6KQEvJRMWobHYZ4FsPFkc+/8A/JaIy2W7CyLZeXRc7lNW6uMLJkjD+4brhHAemtYcgEOGU/ajuX44YTrQez7aG7B3QgfeDulN5BhEH72qWPr1ECSEsQh4AgyHTb7Bq7qWg7AokR3UEDBuY/+BJ06r9ZYmsG0tf2iv9ZPyIbeqCsNLhObuswCjNHTSM7pkECE20kueF4MfBk4GQwG9S+ThpwIDAQAB'

management:
  endpoints:
    web:
      exposure:
        include: "*"
